name: Swift

on:



  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Select Xcode
      run: sudo xcode-Select -switch /Application/Xcode
    - name: Xcode version
      run: /usr/bin/xcodebuild - version
    - name: Build archive
      run: |
            xcodebuild -sdk iphoneos - project DemoCICD/DemoCICD.xcodeproj \
            - configuration Release -scheme DemoCICD \
            - derivedDataPath
    
